(defproject lazybot "0.7.0-SNAPSHOT"
  :description "FIXME: write"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/tools.reader "0.8.5"]
                 [commons-lang/commons-lang "2.6"]
                 [commons-io/commons-io "2.4"]
                 [me.raynes/moments "0.1.1" :exclusions [org.flatland/useful]]
                 [me.raynes/least "0.1.5"]
                 [me.raynes/laser "1.1.1"]
                 [useful "0.8.8"]
                 [clj-twitch "0.1.0-SNAPSHOT"]
                 [clj-time "0.7.0"]
                 [clojail "1.0.6"]
                 [clj-http "0.9.2"]
                 [irclj "0.5.0-alpha4"]
                 [congomongo "0.4.4"]
                 [clj-config "0.2.0"]
                 [ring/ring-jetty-adapter "1.3.0"]
                 [compojure "1.1.8"]
                 [log4j "1.2.17"]
                 [org.thnetos/cd-client "0.3.6"]
                 [org.jruby/jruby "1.7.12"]
                 [clj-wordnik "0.1.0-alpha1"]
                 [cheshire "5.3.1"]
                 [org.clojure/tools.logging "0.3.0"]
                 [org.clojure/data.zip "0.1.1"]
                 [org.clojure/tools.cli "0.3.1"]
                 [hobbit "0.1.0-alpha1"]
                 [ororo "0.1.0"]
                 [socrates "0.0.1"]
                 [innuendo "0.1.7"]
                 [tentacles "0.2.7"]
                 [findfn "0.1.3"]
                 [hiccup "1.0.5"]]
  :jvm-opts ["-Djava.security.policy=example.policy"]
  :uberjar-name "lazybot.jar"
  :main lazybot.run
  :copy-deps true
  :resources-path "resources")
